added handling of Info Service interface

diff --git a/etc/glite-info-dynamic-storm b/etc/glite-info-dynamic-storm
--- a/etc/glite-info-dynamic-storm
+++ b/etc/glite-info-dynamic-storm
@@ -19,34 +19,21 @@
 #
 function get_used_size_kb () {
 
+  cmd="/usr/bin/curl"
+  used=`curl -s 'http://$4:$5/info/status/$1' | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^used-space/ {print $2}'`
+  if [ -z ${used} ]; then
+    echo "ERROR: ${cmd} return no value; check storm info service status."
+    exit 1
+  fi  
+
   # Quota on
-  if ! [ `echo $@ | wc -w` = 2 ] && [ "$3" == "true" ]; then
-    gpfs_quota_cmd="/usr/lpp/mmfs/bin/mmlsquota"
-    if ! [ -z "$4" ] && ! [ -z "$5" ]; then
-      used=`${gpfs_quota_cmd} -j $4 $5 | awk 'NR==3 {print $3}' | sed 's/\..*//'`
-      if [ -z ${used} ]; then
-        echo "ERROR: ${gpfs_quota_cmd} return no value; check GPFS partition." 
-        exit 1
-      fi
-      # convert in kB (base 10)
-      used=$((${used}*1024/1000))
-    else
-      # Missing fileset, device or both
-      used=-1
-    fi
+  if [ "$3" == "true" ]; then
+    # convert in kB (base 10)
+    used=$((${used}*1024/1000))
   # Quota off
   else
-    # Get values from the storm_be_ISAM database
-    total=`echo "SELECT total_size FROM storage_space WHERE space_file='$1' limit 1;" | mysql --user=${STORM_USER} --password=${STORM_DB_PWD} -N storm_be_ISAM`   # in B
-    free=`echo "SELECT free_size FROM storage_space WHERE space_file='$1' limit 1;" | mysql --user=${STORM_USER} --password=${STORM_DB_PWD} -N storm_be_ISAM`   # in B
-    if [ ! -z "${free}" ] && [ ! -z "${total}" ]; then
-      used=$((${total}-${free}))
-      # convert in kB (base 10)
-      used=$((${used}/1000))
-    else
-      # Missing sizes
-      used=-1
-    fi
+    # convert in kB (base 10)
+    used=$((${used}/1000))
   fi
 
   export $2=${used}
@@ -60,34 +47,21 @@ function get_used_size_kb () {
 #
 function get_used_size_gb () {
 
+  cmd="/usr/bin/curl"
+  used=`curl -s 'http://$4:$5/info/status/$1' | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^used-space/ {print $2}'`
+  if [ -z ${used} ]; then
+    echo "ERROR: ${cmd} return no value; check storm info service status."
+    exit 1
+  fi
+
   # Quota on
-  if ! [ `echo $@ | wc -w` = 2 ] && [ "$3" == "true" ]; then
-    gpfs_quota_cmd="/usr/lpp/mmfs/bin/mmlsquota"
-    if ! [ -z "$4" ] && ! [ -z "$5" ]; then
-      used=`${gpfs_quota_cmd} -j $4 $5 | awk 'NR==3 {print $3}' | sed 's/\..*//'`
-      if [ -z ${used} ]; then
-        echo "ERROR: ${gpfs_quota_cmd} return no value; check GPFS partition." 
-        exit 1
-      fi
-      # convert in GB (base 10)
-      used=$((${used}*1024/(1000*1000*1000)))
-    else
-      # Missing fileset or device or both
-      used=-1
-    fi
+  if [ "$3" == "true" ]; then
+    # convert in GB (base 10)
+    used=$((${used}*1024/(1000*1000*1000)))
   # Quota off
   else
-    # Get values from the storm_be_ISAM database
-    total=`echo "SELECT total_size FROM storage_space WHERE space_file='$1' limit 1;" | mysql --user=${STORM_USER} --password=${STORM_DB_PWD} -N storm_be_ISAM`   # in B
-    free=`echo "SELECT free_size FROM storage_space WHERE space_file='$1' limit 1;" | mysql --user=${STORM_USER} --password=${STORM_DB_PWD} -N storm_be_ISAM`   # in B
-    if [ ! -z "${free}" ] && [ ! -z "${total}" ]; then
-      used=$((${total}-${free}))
-      # convert in GB (base 10)
-      used=$((${used}/(1000*1000*1000)))
-    else
-      # Missing sizes
-      used=-1
-    fi
+    # convert in GB (base 10)
+    used=$((${used}/(1000*1000*1000)))
   fi
 
   export $2=${used}
@@ -101,34 +75,21 @@ function get_used_size_gb () {
 #
 function get_free_size_kb () {
 
+  cmd="/usr/bin/curl"
+  free=`curl -s 'http://$4:$5/info/status/$1' | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^free-space/ {print $2}'`
+  if [ -z ${free} ]; then
+    echo "ERROR: ${cmd} return no value; check storm info service status."
+    exit 1
+  fi
+
   # Quota on
-  if ! [ `echo $@ | wc -w` = 2 ] && [ "$3" == "true" ]; then
-    gpfs_quota_cmd="/usr/lpp/mmfs/bin/mmlsquota"
-    if ! [ -z "$4" ] && ! [ -z "$5" ]; then
-      total=`${gpfs_quota_cmd} -j $4 $5 | awk 'NR==3 {printf $4}' | sed 's/\..*//'`
-      used=`${gpfs_quota_cmd} -j $4 $5 | awk 'NR==3 {printf $3}' | sed 's/\..*//'`
-      if [ -z ${total} ] || [ -z ${used} ]; then
-        echo "ERROR: ${gpfs_quota_cmd} return no value; check GPFS partition." 
-        exit 1
-      fi
-      free=$((${total}-${used}))
-      # convert in kB (base 10)
-      free=$((${free}*1024/1000))
-    else
-      # Missing fileset or device or both
-      free=-1
-    fi
+  if [ "$3" == "true" ]; then
+    # convert in kB (base 10)
+    free=$((${free}*1024/1000))
   # Quota off
   else
-    # Get values from the storm_be_ISAM database
-    free=`echo "SELECT free_size FROM storage_space WHERE space_file='$1' limit 1;" | mysql --user=${STORM_USER} --password=${STORM_DB_PWD} -N storm_be_ISAM`   # in B
-    if [ ! -z "${free}" ]; then
-      # convert in kB (base 10)
-      free=$((${free}/1000))
-    else
-      # Missing sizes
-      free=-1
-    fi
+    # convert in kB (base 10)
+    free=$((${free}/1000))
   fi
 
   export $2=${free}
@@ -142,34 +103,21 @@ function get_free_size_kb () {
 #
 function get_free_size_gb () {
 
+  cmd="/usr/bin/curl"
+  free=`curl -s 'http://$4:$5/info/status/$1' | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^free-space/ {print $2}'`
+  if [ -z ${free} ]; then
+    echo "ERROR: ${cmd} return no value; check storm info service status."
+    exit 1
+  fi
+
   # Quota on
-  if ! [ `echo $@ | wc -w` = 2 ] && [ "$3" == "true" ]; then
-    gpfs_quota_cmd="/usr/lpp/mmfs/bin/mmlsquota"
-    if ! [ -z "$4" ] && ! [ -z "$5" ]; then
-      total=`${gpfs_quota_cmd} -j $4 $5 | awk 'NR==3 {printf $4}' | sed 's/\..*//'`
-      used=`${gpfs_quota_cmd} -j $4 $5 | awk 'NR==3 {printf $3}' | sed 's/\..*//'`
-      if [ -z ${total} ] || [ -z ${used} ]; then
-        echo "ERROR: ${gpfs_quota_cmd} return no value; check GPFS partition." 
-        exit 1
-      fi
-      free=$((${total}-${used}))
-      # convert in GB (base 10)
-      free=$((${free}*1024/(1000*1000*1000)))
-    else
-      # Missing fileset or device or both
-      free=-1
-    fi
+  if [ "$3" == "true" ]; then
+    # convert in GB (base 10)
+    free=$((${free}*1024/(1000*1000*1000)))
   # Quota off
   else
-    # Get values from the storm_be_ISAM database
-    free=`echo "SELECT free_size from storage_space WHERE space_file='$1' limit 1;" | mysql --user=${STORM_USER} --password=${STORM_DB_PWD} -N storm_be_ISAM`   # in B
-    if [ ! -z "${free}" ]; then
-      # convert in GB (base 10)
-      free=$((${free}/(1000*1000*1000)))
-    else
-      # Missing sizes
-      free=-1
-    fi
+    # convert in GB (base 10)
+    free=$((${free}/(1000*1000*1000)))
   fi
 
   export $2=${free}
@@ -183,32 +131,21 @@ function get_free_size_gb () {
 #
 function get_total_size_kb () {
 
+  cmd="/usr/bin/curl"
+  total=`curl -s 'http://$4:$5/info/status/$1' | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^total-space/ {print $2}'`
+  if [ -z ${free} ]; then
+    echo "ERROR: ${cmd} return no value; check storm info service status."
+    exit 1
+  fi
+
   # Quota on
-  if ! [ `echo $@ | wc -w` = 2 ] && [ "$3" == "true" ]; then
-    gpfs_quota_cmd="/usr/lpp/mmfs/bin/mmlsquota"
-    if ! [ -z "$4" ] && ! [ -z "$5" ]; then
-      total=`${gpfs_quota_cmd} -j $4 $5 | awk 'NR==3 {printf $4}' | sed 's/\..*//'`
-      if [ -z ${total} ]; then
-        echo "ERROR: ${gpfs_quota_cmd} return no value; check GPFS partition." 
-        exit 1
-      fi
-      # convert in kB (base 10)
-      total=$((${total}*1024/1000))
-    else
-      # Missing fileset or device or both
-      total=-1
-    fi
+  if [ "$3" == "true" ]; then
+    # convert in kB (base 10)
+    total=$((${total}*1024/1000))
   # Quota off
   else
-    # Get values from the storm_be_ISAM database
-    total=`echo "SELECT total_size FROM storage_space WHERE space_file='$1' limit 1;" | mysql --user=${STORM_USER} --password=${STORM_DB_PWD} -N storm_be_ISAM`   # in B
-    if [ ! -z "${total}" ]; then
-      # convert in kB (base 10)
-      total=$((${total}/1000))
-    else
-      # Missing sizes
-      total=-1
-    fi
+    # convert in kB (base 10)
+    total=$((${total}/1000))
   fi
 
   export $2=${total}
@@ -222,32 +159,21 @@ function get_total_size_kb () {
 #
 function get_total_size_gb () {
 
+  cmd="/usr/bin/curl"
+  total=`curl -s 'http://$4:$5/info/status/$1' | sed -e 's/[{}]/''/g' | awk -v RS=',"' -F: '/^total-space/ {print $2}'`
+  if [ -z ${free} ]; then
+    echo "ERROR: ${cmd} return no value; check storm info service status."
+    exit 1
+  fi
+
   # Quota on
-  if ! [ `echo $@ | wc -w` = 2 ] && [ "$3" == "true" ]; then
-    gpfs_quota_cmd="/usr/lpp/mmfs/bin/mmlsquota"
-    if ! [ -z "$4" ] && ! [ -z "$5" ]; then
-      total=`${gpfs_quota_cmd} -j $4 $5 | awk 'NR==3 {printf $4}' | sed 's/\..*//'`
-      if [ -z ${total} ]; then
-        echo "ERROR: ${gpfs_quota_cmd} return no value; check GPFS partition." 
-        exit 1
-      fi
-      # convert in GB (base 10)
-      total=$((${total}*1024/(1000*1000*1000)))
-    else
-      # Missing fileset or device or both
-      total=-1
-    fi
+  if [ "$3" == "true" ]; then
+    # convert in GB (base 10)
+    total=$((${total}*1024/(1000*1000*1000)))
   # Quota off
   else
-    # Get values from the storm_be_ISAM database
-    total=`echo "SELECT total_size FROM storage_space WHERE space_file='$1' limit 1;" | mysql --user=${STORM_USER} --password=${STORM_DB_PWD} -N storm_be_ISAM`   # in B
-    if [ ! -z "${total}" ]; then
-      # convert in GB (base 10)
-      total=$((${total}/(1000*1000*1000)))
-    else
-      # Missing sizes
-      total=-1
-    fi
+    # convert in GB (base 10)
+    total=$((${total}/(1000*1000*1000)))
   fi
 
   export $2=${total}
@@ -287,23 +213,22 @@ function get_total_size_gb () {
     # Remove DNS-like characters from SA_UPP names
     SA_UPP=`echo ${SA_UPP} | sed -e 's/-//g' -e 's/\.//g'`
 
-    x=STORM_${SA_UPP}_ROOT;            SA_ROOT=${!x:-${STORM_DEFAULT_ROOT}/${SA_LOW}}
+    x=STORM_${SA_UPP}_TOKEN;           SA_TOKEN=${!x:-${SA_UPP}_TOKEN}
     x=STORM_${SA_UPP}_QUOTA;           SA_QUOTA=${!x}
-    x=STORM_${SA_UPP}_QUOTA_FILESET;   SA_FILESET=${!x}
-    x=STORM_${SA_UPP}_QUOTA_DEVICE;    SA_DEVICE=${!x}
     x=STORM_${SA_UPP}_VONAME;          SA_VONAME=${!x:-${SA_LOW}}
 
-    # Get size values on SA_ROOT (in GB)
-    get_used_size_gb  ${SA_ROOT} PARAMETER ${SA_QUOTA} ${SA_FILESET} ${SA_DEVICE}
-    hash_insert SA_USED_SIZE_GB  ${SA_UPP} ${PARAMETER}
-    get_free_size_gb  ${SA_ROOT} PARAMETER ${SA_QUOTA} ${SA_FILESET} ${SA_DEVICE}
+    # Get size values on SA_TOKEN (in GB)
+    get_used_size_gb  ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_INFO_SERVICE_HOST} ${STORM_INFO_SERVICE_PORT}
+    hash_insert SA_USED_SIZE_GB  ${SA_UPP} ${PARAMETER} 
+    get_free_size_gb  ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_INFO_SERVICE_HOST} ${STORM_INFO_SERVICE_PORT}
     hash_insert SA_FREE_SIZE_GB  ${SA_UPP} ${PARAMETER}
-    get_total_size_gb ${SA_ROOT} PARAMETER ${SA_QUOTA} ${SA_FILESET} ${SA_DEVICE}
+    get_total_size_gb ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_INFO_SERVICE_HOST} ${STORM_INFO_SERVICE_PORT}
     hash_insert SA_TOTAL_SIZE_GB ${SA_UPP} ${PARAMETER}
-    # Get size values on SA_ROOT (in KB)
-    get_used_size_kb  ${SA_ROOT} PARAMETER ${SA_QUOTA} ${SA_FILESET} ${SA_DEVICE}
+
+    # Get size values on SA_TOKEN (in KB)
+    get_used_size_kb  ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_INFO_SERVICE_HOST} ${STORM_INFO_SERVICE_PORT}
     hash_insert SA_USED_SIZE_KB  ${SA_UPP} ${PARAMETER}
-    get_free_size_kb  ${SA_ROOT} PARAMETER ${SA_QUOTA} ${SA_FILESET} ${SA_DEVICE}
+    get_free_size_kb  ${SA_TOKEN} PARAMETER ${SA_QUOTA} ${STORM_INFO_SERVICE_HOST} ${STORM_INFO_SERVICE_PORT}
     hash_insert SA_FREE_SIZE_KB  ${SA_UPP} ${PARAMETER}
 
     # Prepare per-VO and global values
